twirphp/twirp

CHANGELOG.md, protoc-gen-twirp_php/templates/global/TwirpClient.php, protoc-gen-twirp_php/templates/service/Client.php
| Bug fix?        | no
| New feature?    | yes
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | fixes #9
The client does not invoke the message factory in the constructor anymore to create the base URL.
It was not really nice to invoke any code in the constructor. It also made using mocks harder.
=> Do not use the message factory in the constructor

composer.json
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | fixes #17
=> Add version conflict to composer for protobuf package lower than 3.5

protoc-gen-twirp_php/templates/global/TwirpError.php
Applies for php 7.1+
Otherwise generated class throw
```
Fatal error: Declaration of ...TwirpError::getMeta($key): string must be compatible with Twirp\Error::getMeta(string $key): string
```
=> Prevent fatal error because of generated class contract incompatibility

protoc-gen-twirp_php/internal/php/func.go
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | fixes #35
When there are no options defined in a proto file, the options descriptor struct will be nil.
The namespace generator function used this struct regardless of that fact which caused a panic.
=> Fix panic when no proto options are defined

protoc-gen-twirp_php/templates/service/Server.php
| Bug fix?        | no
| New feature?    | yes
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | fixes #46
**What's in this PR?**
When decoding JSON, Twirp (Go) allows unknown fields. See example.
In Protobuf 3.12, an option was added to ignore unknown fields for PHP. The runtime behavior varies depending on whether or not you have the Protobuf extension installed. See protocolbuffers/protobuf#8514.
**Why?**
To mirror twitchtv/twirp, twirphp should allow unknown fields when unmarshalling JSON.
**Example Usage**
See https://github.com/mterwill/proto-unknown-fields
**Attribution**
Originally submitted by @mterwill in #46, resubmitted to resolve conflicts
=> Ignore unkown fields

composer.json
**What's in this PR?**
Exclude protoc-gen-twirp_php and other unneeded files from the composer archive. They are not needed by users.
**Why?**
We do not need to include the generator code - php templates and go - in the composer archive.  This can be confusing and/or pollute users projects.
=> Exclude protoc-gen-twirp_php from composer archive

CHANGELOG.md, protoc-gen-twirp_php/main.go
| Bug fix?        |yes
| New feature?    | no|
| BC breaks?      | no|yes
| Deprecations?   | no|
| Related tickets | -
**What's in this PR?**
This fixes a bug in protoc-gen-twirp_php that occurs when compiling an input file that does not specify any options.
**Why?**
The following is a valid protobuf file:
```proto
syntax = "proto3";
package foo;
service Foo {
}
```
Currently when you run protoc-gen-twirp_php against this file, it segfaults:
```
$ protoc --twirp_php_out=gen/ foo.proto
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x13b867b]
goroutine 1 [running]:
main.Main(0x14f4220, 0xc000010010, 0x14f4240, 0xc000010018, 0x0, 0x0) …
```
=> fix: segfault when input proto file does not specify options

CHANGELOG.md, protoc-gen-twirp_php/internal/php/func.go
| Bug fix?        |yes
| New feature?    | no|
| BC breaks?      | no|
| Deprecations?   | no|
| Related tickets | -
**What's in this PR? Why?**
protoc-gen-twirp_php currently incorrectly namespaces messages when importing other files with different namespaces. Instead of passing around the file we're generating to determine a message name, we should use the message's parent file. There's some proto type juggling involved here; I did the best I could to not make the change too intrusive.
On main right now:
```
$ ./test.sh
23c23
<     public function Foo(array $ctx, \Bar\Bar $req): \Google\Protobuf\GPBEmpty;
---
>     public function Foo(array $ctx, \Foo\Bar $req): \Foo\PBEmpty;
```
**Checklist**
**To Do**
=> fix: namespacing bug when importing other proto files

CHANGELOG.md, example/generated/Twitch/Twirp/Example/TwirpError.php, example/tests/TwirpErrorTest.php, protoc-gen-twirp_php/templates/global/TwirpError.php.tmpl
| Bug fix?        | yes|
| New feature?    | no|
| BC breaks?      | no|
| Deprecations?   | no|
**What's in this PR?**
While `Exception->getCode` is typed to return an int, it's still not guaranteed to. See: https://www.php.net/manual/en/exception.getcode.php
> Returns the exception code as int in Exception but possibly as other type in Exception descendants (for example as string in PDOException).
Ensure the code is an int before passing it into the constructor. String codes will still be accessible via the previous exception.
**Why?**
So that we do not inadvertently throw a `TypeError`.
**Checklist**
=> bugfix: Ensure error code is an int

example/server.php, example/tests/HaberdasherFunctionalTest.php, example/tests/HaberdasherServerTest.php, protoc-gen-twirp_php/templates/service/Server.php.tmpl
**Overview**
Add support for server path prefix.
As of the v7 spec, Twirp allows changing the URL prefix applied to each service.
The client already supported changing the prefix. This PR adds support for changing the prefix on the server side.
```release-note
- Consumers should now use `getPathPrefix()` instead of `PATH_PREFIX` constants
```
=> Server path prefix

example/server.php, lib/src/Router.php, lib/tests/RouterTest.php, phpstan-baseline.neon
**Overview**
Add a new Router that replaces Server.
We will likely want to use the name Server for something else.
Also, Router uses more generic terms as path (instead of prefix) and handler (instead of server).
Related #88
Related #89
```release-note
Deprecated `Server`. Use `Router` instead.
```
=> Add Router instead of server

example/tests/HaberdasherFunctionalTest.php, protoc-gen-twirp_php/templates/service/Server.php.tmpl
**Overview**
Return error if the service name matches, but the prefix doesn't.
v7 spec made it possible to replace the /twirp prefix with custom prefixes.
I guess this extra check is in there to help clients address prefix issues instead of getting weird not found errors.
```release-note
Non-matching prefix is now returned as a separate error.
```
=> Return error on prefix mismatch

protoc-gen-twirp_php/templates/service/AbstractClient.php.tmpl
**Overview**
Return HTTP 429 as resource exhausted error
As of v7 spec resource exhausted error is returned as HTTP 429 status code.
This PR fixes the generated client to return that same error when it sees an HTTP 429 response.
```release-note
Return HTTP 429 as resource exhausted error
```
=> Return HTTP 429 as resource exhausted error

README.md
**Overview**
Fixed installation instruction in readme. Its need to pass `-b` flag after `-s --` construction
=> fix: fixed installation command with curl in readme

protoc-gen-twirp_php/internal/gen/generator.go
**Overview**
Only generate global templates when there are services in a namespace
Fixes #100
```release-note
TwirpError won't be generated when no services are present in a namespace
```
=> Only generate global templates when there are services in a namespace

install.sh
The generated install.sh was missing the entries for arm64, even though goreleaser already builds the respective packages.
=> Allow using the install script on arm64

composer.json, protoc-gen-twirp_php/templates/service/Server.php.tmpl
**Overview**
Fix spec violation reported in #158
Fixes #158
=> Fix meta serialization

protoc-gen-twirp_php/templates/global/TwirpError.php.tmpl, protoc-gen-twirp_php/templates/service/AbstractClient.php.tmpl, protoc-gen-twirp_php/templates/service/Server.php.tmpl
**Overview**
Fix implicitly null parameter types in templates.
In PHP 8.4, implicitly nullable parameter types will be deprecated. Read [the RFC](https://wiki.php.net/rfc/deprecate-implicitly-nullable-types) for more details. This change will prevent a deprecation warning once PHP 8.4 is released. It has no effect on earlier PHP versions.
Instances of this were already fixed via php-cs-fixer in non-templated code, so this is also more consistent within the code base.
```release-note
Prevent deprecation warnings on PHP 8.4.
```
=> Fix implicitly null parameter types in templates

protoc-gen-twirp_php/internal/php/func.go, tests/namespace/test.php
**Overview**
Fix nested message name generation
Updated PHP name generation based on the original compiler code: https://github.com/protocolbuffers/protobuf/blob/6e393fd79667597aac2bb42511fb30c31ff1611d/src/google/protobuf/compiler/php/names.cc
Fixes #201
Fixes #203
=> Fix nested message name generation

composer.json
**Overview**
Replacement for:
- #124
Allows to use this package with modern software.
I checked which versions are supported commonly:
```
guzzlehttp/psr7                 2.7.1                                           requires psr/http-message (^1.1 || ^2.0) 
php-http/client-common          2.7.2                                           requires psr/http-message (^1.0 || ^2.0) 
php-http/httplug                2.4.1                                           requires psr/http-message (^1.0 || ^2.0) 
php-http/httplug-bundle         2.1.0                                           requires psr/http-message (^1.0 || ^2.0) 
php-http/message                1.16.2                                          requires …
```
=> Add psr/http-message v2 support

protoc-gen-twirp_php/templates/service/AbstractClient.php.tmpl
**Overview**
Looks like a typo in DocBlock.
=> Fix AbstractClient.php.tmpl property type
